receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
    send_batch_size: 10  # Number of objects which will be sent in each batch
    #send_batch_size: 8192  # Number of objects which will be sent in each batch
    timeout: 200ms  # Time after which a batch will be sent anyway, regardless of size
    send_batch_max_size: 0  # Upper limit of the batch size, 0=no upper limit

  #attributes:
  #  actions:
  #  - action: insert
  #    key: loki.attribute.labels
  #    value: http.status_code

extensions:
  basicauth/otlp:
    client_auth:
      username: ${env:OTLP_USER}
      password: ${env:OTLP_PASS} 

exporters:
  otlphttp:
    auth:
      authenticator: basicauth/otlp
    endpoint: https://otlp-gateway-prod-us-east-0.grafana.net/otlp
  logging:
    verbosity: detailed

service:
  extensions: [basicauth/otlp]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      #exporters: [logging]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
      ##exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
      #exporters: [logging]
